### PR TITLE
Additional Information in Detector API

### PR DESCRIPTION
**Pull request by vaughantnrc**

### CODE REVIEW

**Comment by vaughantnrc** [comment]
Good point. I'm not currently planning any other API changes. That could change though. Let's wait a few days and see where we're at. I don't think either of the commits in this PR should affect the work that you or David are doing right at the moment (though for an accuracy evaluation we do want a correct detector frame timestamp).

**Comment by keiranbarr** [comment]
By my testing I think merging this PR would require an update of the Pi OS images. I get the following error when trying to connect to the detector (running the current main code) from the GUI (running this PR):

> ERROR:src.common.status_message_source:source_label='controller' severity='error' message='Exception occurred in controller loop: ()' timestamp_utc_iso8601='2024-07-23T19:47:59.719988'

I can definitely update the OS images and merge this, it is not a problem. As you said, it is important to have a correct detector timestamp.

**Comment by vaughantnrc** [comment]
Yes, I meant to say that the change will not have any direct impact on the work you are doing, BUT you are right that it would need an updated Pi image. So I suggest let's wait a few days.

**Comment by keiranbarr** [comment]
Ah yes I see, thanks for the clarification. That all sounds good to me.

**Comment by vaughantnrc** [comment]
@keiranbarr I'm going to add requested resolution as per https://github.com/PerkLab/MCSTrack/issues/71

Then we can do the merge. Does that sound ok to you?

**Pull request merged**
